/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastreportCloudSdk);
  }
}(this, function(expect, FastreportCloudSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastreportCloudSdk.SubscriptionPlanVM();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubscriptionPlanVM', function() {
    it('should create an instance of SubscriptionPlanVM', function() {
      // uncomment below and update the code to test SubscriptionPlanVM
      //var instane = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be.a(FastreportCloudSdk.SubscriptionPlanVM);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "isActive")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property timePeriodType (base name: "timePeriodType")', function() {
      // uncomment below and update the code to test the property timePeriodType
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property timePeriod (base name: "timePeriod")', function() {
      // uncomment below and update the code to test the property timePeriod
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property readonlyTimeLimitType (base name: "readonlyTimeLimitType")', function() {
      // uncomment below and update the code to test the property readonlyTimeLimitType
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property readonlyTimeLimit (base name: "readonlyTimeLimit")', function() {
      // uncomment below and update the code to test the property readonlyTimeLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property templatesSpaceLimit (base name: "templatesSpaceLimit")', function() {
      // uncomment below and update the code to test the property templatesSpaceLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property reportsSpaceLimit (base name: "reportsSpaceLimit")', function() {
      // uncomment below and update the code to test the property reportsSpaceLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property exportsSpaceLimit (base name: "exportsSpaceLimit")', function() {
      // uncomment below and update the code to test the property exportsSpaceLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property fileUploadSizeLimit (base name: "fileUploadSizeLimit")', function() {
      // uncomment below and update the code to test the property fileUploadSizeLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property dataSourceLimit (base name: "dataSourceLimit")', function() {
      // uncomment below and update the code to test the property dataSourceLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property maxUsersCount (base name: "maxUsersCount")', function() {
      // uncomment below and update the code to test the property maxUsersCount
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property hasSpaceOverdraft (base name: "hasSpaceOverdraft")', function() {
      // uncomment below and update the code to test the property hasSpaceOverdraft
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property groupLimit (base name: "groupLimit")', function() {
      // uncomment below and update the code to test the property groupLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property onlineDesigner (base name: "onlineDesigner")', function() {
      // uncomment below and update the code to test the property onlineDesigner
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property isDemo (base name: "isDemo")', function() {
      // uncomment below and update the code to test the property isDemo
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property urlToBuy (base name: "urlToBuy")', function() {
      // uncomment below and update the code to test the property urlToBuy
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property unlimitedPage (base name: "unlimitedPage")', function() {
      // uncomment below and update the code to test the property unlimitedPage
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property pageLimit (base name: "pageLimit")', function() {
      // uncomment below and update the code to test the property pageLimit
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

    it('should have the property tasks (base name: "tasks")', function() {
      // uncomment below and update the code to test the property tasks
      //var instance = new FastreportCloudSdk.SubscriptionPlanVM();
      //expect(instance).to.be();
    });

  });

}));
