/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastreportCloudSdk);
  }
}(this, function(expect, FastreportCloudSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastreportCloudSdk.TaskSettingsVM();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TaskSettingsVM', function() {
    it('should create an instance of TaskSettingsVM', function() {
      // uncomment below and update the code to test TaskSettingsVM
      //var instane = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be.a(FastreportCloudSdk.TaskSettingsVM);
    });

    it('should have the property prepare (base name: "prepare")', function() {
      // uncomment below and update the code to test the property prepare
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

    it('should have the property exportTemplate (base name: "exportTemplate")', function() {
      // uncomment below and update the code to test the property exportTemplate
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

    it('should have the property exportReport (base name: "exportReport")', function() {
      // uncomment below and update the code to test the property exportReport
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

    it('should have the property sendViaEmail (base name: "sendViaEmail")', function() {
      // uncomment below and update the code to test the property sendViaEmail
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

    it('should have the property sendViaWebhook (base name: "sendViaWebhook")', function() {
      // uncomment below and update the code to test the property sendViaWebhook
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

    it('should have the property fetchData (base name: "fetchData")', function() {
      // uncomment below and update the code to test the property fetchData
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailReport (base name: "thumbnailReport")', function() {
      // uncomment below and update the code to test the property thumbnailReport
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailTemplate (base name: "thumbnailTemplate")', function() {
      // uncomment below and update the code to test the property thumbnailTemplate
      //var instance = new FastreportCloudSdk.TaskSettingsVM();
      //expect(instance).to.be();
    });

  });

}));
