/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FolderCreateVM from './FolderCreateVM';

/**
 * The AdminFolderCreateVM model module.
 * @module models/AdminFolderCreateVM
 * @version v1
 */
class AdminFolderCreateVM {
    /**
     * Constructs a new <code>AdminFolderCreateVM</code>.
     * @alias module:models/AdminFolderCreateVM
     * @extends module:models/FolderCreateVM
     * @implements module:models/FolderCreateVM
     */
    constructor() { 
        FolderCreateVM.initialize(this);
        AdminFolderCreateVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['parentId'] = parentId;
        obj['ownerId'] = ownerId;
    }

    /**
     * Constructs a <code>AdminFolderCreateVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AdminFolderCreateVM} obj Optional instance to populate.
     * @return {module:models/AdminFolderCreateVM} The populated <code>AdminFolderCreateVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdminFolderCreateVM();
            FolderCreateVM.constructFromObject(data, obj);
            FolderCreateVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('ownerId')) {
                obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'String');
            }
            if (data.hasOwnProperty('force')) {
                obj['force'] = ApiClient.convertToType(data['force'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AdminFolderCreateVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AdminFolderCreateVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AdminFolderCreateVM.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['parentId'] && !(typeof data['parentId'] === 'string' || data['parentId'] instanceof String)) {
            throw new Error("Expected the field `parentId` to be a primitive type in the JSON string but got " + data['parentId']);
        }
        // ensure the json data is a string
        if (data['ownerId'] && !(typeof data['ownerId'] === 'string' || data['ownerId'] instanceof String)) {
            throw new Error("Expected the field `ownerId` to be a primitive type in the JSON string but got " + data['ownerId']);
        }

        return true;
    }


}

AdminFolderCreateVM.RequiredProperties = ["parentId", "ownerId"];

/**
 * @member {String} parentId
 */
AdminFolderCreateVM.prototype['parentId'] = undefined;

/**
 * @member {String} ownerId
 */
AdminFolderCreateVM.prototype['ownerId'] = undefined;

/**
 * @member {Boolean} force
 */
AdminFolderCreateVM.prototype['force'] = undefined;


// Implement FolderCreateVM interface:
/**
 * @member {String} name
 */
FolderCreateVM.prototype['name'] = undefined;
/**
 * @member {Array.<String>} tags
 */
FolderCreateVM.prototype['tags'] = undefined;
/**
 * @member {Blob} icon
 */
FolderCreateVM.prototype['icon'] = undefined;




export default AdminFolderCreateVM;

