/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdminFolderCreateVM from './AdminFolderCreateVM';

/**
 * The AdminTemplateFolderCreateVM model module.
 * @module models/AdminTemplateFolderCreateVM
 * @version v1
 */
class AdminTemplateFolderCreateVM {
    /**
     * Constructs a new <code>AdminTemplateFolderCreateVM</code>.
     * @alias module:models/AdminTemplateFolderCreateVM
     * @implements module:models/AdminFolderCreateVM
     */
    constructor() { 
        AdminFolderCreateVM.initialize(this);
        AdminTemplateFolderCreateVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdminTemplateFolderCreateVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AdminTemplateFolderCreateVM} obj Optional instance to populate.
     * @return {module:models/AdminTemplateFolderCreateVM} The populated <code>AdminTemplateFolderCreateVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdminTemplateFolderCreateVM();
            AdminFolderCreateVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'Blob');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
AdminTemplateFolderCreateVM.prototype['name'] = undefined;

/**
 * @member {Array.<String>} tags
 */
AdminTemplateFolderCreateVM.prototype['tags'] = undefined;

/**
 * @member {Blob} icon
 */
AdminTemplateFolderCreateVM.prototype['icon'] = undefined;


// Implement AdminFolderCreateVM interface:
/**
 * @member {String} name
 */
AdminFolderCreateVM.prototype['name'] = undefined;
/**
 * @member {Array.<String>} tags
 */
AdminFolderCreateVM.prototype['tags'] = undefined;
/**
 * @member {Blob} icon
 */
AdminFolderCreateVM.prototype['icon'] = undefined;




export default AdminTemplateFolderCreateVM;

