/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuditActionVM from './AuditActionVM';

/**
 * The AuditActionsVM model module.
 * @module models/AuditActionsVM
 * @version v1
 */
class AuditActionsVM {
    /**
     * Constructs a new <code>AuditActionsVM</code>.
     * @alias module:models/AuditActionsVM
     */
    constructor() { 
        
        AuditActionsVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuditActionsVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AuditActionsVM} obj Optional instance to populate.
     * @return {module:models/AuditActionsVM} The populated <code>AuditActionsVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditActionsVM();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [AuditActionVM]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('skip')) {
                obj['skip'] = ApiClient.convertToType(data['skip'], 'Number');
            }
            if (data.hasOwnProperty('take')) {
                obj['take'] = ApiClient.convertToType(data['take'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuditActionsVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuditActionsVM</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                AuditActionVM.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/AuditActionVM>} items
 */
AuditActionsVM.prototype['items'] = undefined;

/**
 * @member {Number} count
 */
AuditActionsVM.prototype['count'] = undefined;

/**
 * @member {Number} skip
 */
AuditActionsVM.prototype['skip'] = undefined;

/**
 * @member {Number} take
 */
AuditActionsVM.prototype['take'] = undefined;






export default AuditActionsVM;

