/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuditActionVM from './AuditActionVM';
import AuditType from './AuditType';

/**
 * The AuditTaskActionVM model module.
 * @module models/AuditTaskActionVM
 * @version v1
 */
class AuditTaskActionVM {
    /**
     * Constructs a new <code>AuditTaskActionVM</code>.
     * @alias module:models/AuditTaskActionVM
     * @extends module:models/AuditActionVM
     * @implements module:models/AuditActionVM
     * @param t {String} 
     */
    constructor(t) { 
        AuditActionVM.initialize(this, t);
        AuditTaskActionVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
    }

    /**
     * Constructs a <code>AuditTaskActionVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AuditTaskActionVM} obj Optional instance to populate.
     * @return {module:models/AuditTaskActionVM} The populated <code>AuditTaskActionVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditTaskActionVM();
            AuditActionVM.constructFromObject(data, obj);
            AuditActionVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuditTaskActionVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuditTaskActionVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuditTaskActionVM.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['messageId'] && !(typeof data['messageId'] === 'string' || data['messageId'] instanceof String)) {
            throw new Error("Expected the field `messageId` to be a primitive type in the JSON string but got " + data['messageId']);
        }

        return true;
    }


}

AuditTaskActionVM.RequiredProperties = ["$t"];

/**
 * @member {String} messageId
 */
AuditTaskActionVM.prototype['messageId'] = undefined;


// Implement AuditActionVM interface:
/**
 * @member {String} userId
 */
AuditActionVM.prototype['userId'] = undefined;
/**
 * @member {String} entityId
 */
AuditActionVM.prototype['entityId'] = undefined;
/**
 * @member {String} subscriptionId
 */
AuditActionVM.prototype['subscriptionId'] = undefined;
/**
 * @member {module:models/AuditType} type
 */
AuditActionVM.prototype['type'] = undefined;
/**
 * @member {String} id
 */
AuditActionVM.prototype['id'] = undefined;
/**
 * @member {Date} createdTime
 */
AuditActionVM.prototype['createdTime'] = undefined;
/**
 * @member {String} creatorUserId
 */
AuditActionVM.prototype['creatorUserId'] = undefined;
/**
 * @member {String} name
 */
AuditActionVM.prototype['name'] = undefined;
/**
 * @member {Boolean} adminAction
 */
AuditActionVM.prototype['adminAction'] = undefined;
/**
 * @member {String} $t
 */
AuditActionVM.prototype['$t'] = undefined;




export default AuditTaskActionVM;

