/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuditActionVM from './AuditActionVM';
import AuditType from './AuditType';

/**
 * The AuditSubscriptionActionVM model module.
 * @module models/AuditSubscriptionActionVM
 * @version v1
 */
class AuditSubscriptionActionVM {
    /**
     * Constructs a new <code>AuditSubscriptionActionVM</code>.
     * @alias module:models/AuditSubscriptionActionVM
     * @extends module:models/AuditActionVM
     * @implements module:models/AuditActionVM
     * @param t {String} 
     */
    constructor(t) { 
        AuditActionVM.initialize(this, t);
        AuditSubscriptionActionVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>AuditSubscriptionActionVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AuditSubscriptionActionVM} obj Optional instance to populate.
     * @return {module:models/AuditSubscriptionActionVM} The populated <code>AuditSubscriptionActionVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditSubscriptionActionVM();
            AuditActionVM.constructFromObject(data, obj);
            AuditActionVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('periodStart')) {
                obj['periodStart'] = ApiClient.convertToType(data['periodStart'], 'Date');
            }
            if (data.hasOwnProperty('periodEnd')) {
                obj['periodEnd'] = ApiClient.convertToType(data['periodEnd'], 'Date');
            }
            if (data.hasOwnProperty('planId')) {
                obj['planId'] = ApiClient.convertToType(data['planId'], 'String');
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuditSubscriptionActionVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuditSubscriptionActionVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuditSubscriptionActionVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['planId'] && !(typeof data['planId'] === 'string' || data['planId'] instanceof String)) {
            throw new Error("Expected the field `planId` to be a primitive type in the JSON string but got " + data['planId']);
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

AuditSubscriptionActionVM.RequiredProperties = ["$t"];

/**
 * @member {Date} periodStart
 */
AuditSubscriptionActionVM.prototype['periodStart'] = undefined;

/**
 * @member {Date} periodEnd
 */
AuditSubscriptionActionVM.prototype['periodEnd'] = undefined;

/**
 * @member {String} planId
 */
AuditSubscriptionActionVM.prototype['planId'] = undefined;

/**
 * @member {String} $t
 */
AuditSubscriptionActionVM.prototype['$t'] = undefined;


// Implement AuditActionVM interface:
/**
 * @member {String} $t
 */
AuditActionVM.prototype['$t'] = undefined;




export default AuditSubscriptionActionVM;

