/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateExportReportTaskVM from './CreateExportReportTaskVM';
import CreateTaskEndVM from './CreateTaskEndVM';
import CreateTransportTaskBaseVM from './CreateTransportTaskBaseVM';
import ExportFormat from './ExportFormat';
import InputFileVM from './InputFileVM';
import OutputFileVM from './OutputFileVM';

/**
 * The CreateExportTemplateTaskVM model module.
 * @module models/CreateExportTemplateTaskVM
 * @version v1
 */
class CreateExportTemplateTaskVM {
    /**
     * Constructs a new <code>CreateExportTemplateTaskVM</code>.
     * @alias module:models/CreateExportTemplateTaskVM
     * @extends module:models/CreateExportReportTaskVM
     * @implements module:models/CreateExportReportTaskVM
     * @param t {String} 
     */
    constructor(t) { 
        CreateExportReportTaskVM.initialize(this, t);
        CreateExportTemplateTaskVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>CreateExportTemplateTaskVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CreateExportTemplateTaskVM} obj Optional instance to populate.
     * @return {module:models/CreateExportTemplateTaskVM} The populated <code>CreateExportTemplateTaskVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateExportTemplateTaskVM();
            CreateExportReportTaskVM.constructFromObject(data, obj);
            CreateExportReportTaskVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('reportParameters')) {
                obj['reportParameters'] = ApiClient.convertToType(data['reportParameters'], {'String': 'String'});
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateExportTemplateTaskVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateExportTemplateTaskVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateExportTemplateTaskVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

CreateExportTemplateTaskVM.RequiredProperties = ["$t"];

/**
 * @member {Object.<String, String>} reportParameters
 */
CreateExportTemplateTaskVM.prototype['reportParameters'] = undefined;

/**
 * @member {String} $t
 */
CreateExportTemplateTaskVM.prototype['$t'] = undefined;


// Implement CreateExportReportTaskVM interface:
/**
 * @member {module:models/InputFileVM} inputFile
 */
CreateExportReportTaskVM.prototype['inputFile'] = undefined;
/**
 * @member {String} locale
 */
CreateExportReportTaskVM.prototype['locale'] = undefined;
/**
 * @member {module:models/OutputFileVM} outputFile
 */
CreateExportReportTaskVM.prototype['outputFile'] = undefined;
/**
 * @member {Array.<module:models/CreateTransportTaskBaseVM>} transports
 */
CreateExportReportTaskVM.prototype['transports'] = undefined;
/**
 * @member {String} $t
 */
CreateExportReportTaskVM.prototype['$t'] = undefined;
/**
 * @member {String} cronExpression
 */
CreateExportReportTaskVM.prototype['cronExpression'] = undefined;
/**
 * @member {Date} startsOn
 */
CreateExportReportTaskVM.prototype['startsOn'] = undefined;
/**
 * @member {module:models/CreateTaskEndVM} ends
 */
CreateExportReportTaskVM.prototype['ends'] = undefined;
/**
 * @member {String} name
 */
CreateExportReportTaskVM.prototype['name'] = undefined;
/**
 * @member {String} subscriptionId
 */
CreateExportReportTaskVM.prototype['subscriptionId'] = undefined;




export default CreateExportTemplateTaskVM;

