/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateTaskBaseVM from './CreateTaskBaseVM';
import CreateTransportTaskBaseVM from './CreateTransportTaskBaseVM';
import InputFileVM from './InputFileVM';
import OutputFileVM from './OutputFileVM';

/**
 * The CreateTransformTaskBaseVM model module.
 * @module models/CreateTransformTaskBaseVM
 * @version v1
 */
class CreateTransformTaskBaseVM {
    /**
     * Constructs a new <code>CreateTransformTaskBaseVM</code>.
     * @alias module:models/CreateTransformTaskBaseVM
     * @extends module:models/CreateTaskBaseVM
     * @implements module:models/CreateTaskBaseVM
     * @param t {String} 
     */
    constructor(t) { 
        CreateTaskBaseVM.initialize(this, t);
        CreateTransformTaskBaseVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>CreateTransformTaskBaseVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CreateTransformTaskBaseVM} obj Optional instance to populate.
     * @return {module:models/CreateTransformTaskBaseVM} The populated <code>CreateTransformTaskBaseVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTransformTaskBaseVM();
            CreateTaskBaseVM.constructFromObject(data, obj);
            CreateTaskBaseVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('inputFile')) {
                obj['inputFile'] = InputFileVM.constructFromObject(data['inputFile']);
            }
            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('outputFile')) {
                obj['outputFile'] = OutputFileVM.constructFromObject(data['outputFile']);
            }
            if (data.hasOwnProperty('transports')) {
                obj['transports'] = ApiClient.convertToType(data['transports'], [CreateTransportTaskBaseVM]);
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateTransformTaskBaseVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateTransformTaskBaseVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateTransformTaskBaseVM.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `inputFile`
        if (data['inputFile']) { // data not null
          InputFileVM.validateJSON(data['inputFile']);
        }
        // ensure the json data is a string
        if (data['locale'] && !(typeof data['locale'] === 'string' || data['locale'] instanceof String)) {
            throw new Error("Expected the field `locale` to be a primitive type in the JSON string but got " + data['locale']);
        }
        // validate the optional field `outputFile`
        if (data['outputFile']) { // data not null
          OutputFileVM.validateJSON(data['outputFile']);
        }
        if (data['transports']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['transports'])) {
                throw new Error("Expected the field `transports` to be an array in the JSON data but got " + data['transports']);
            }
            // validate the optional field `transports` (array)
            for (const item of data['transports']) {
                CreateTransportTaskBaseVM.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

CreateTransformTaskBaseVM.RequiredProperties = ["$t"];

/**
 * @member {module:models/InputFileVM} inputFile
 */
CreateTransformTaskBaseVM.prototype['inputFile'] = undefined;

/**
 * @member {String} locale
 */
CreateTransformTaskBaseVM.prototype['locale'] = undefined;

/**
 * @member {module:models/OutputFileVM} outputFile
 */
CreateTransformTaskBaseVM.prototype['outputFile'] = undefined;

/**
 * @member {Array.<module:models/CreateTransportTaskBaseVM>} transports
 */
CreateTransformTaskBaseVM.prototype['transports'] = undefined;

/**
 * @member {String} $t
 */
CreateTransformTaskBaseVM.prototype['$t'] = undefined;


// Implement CreateTaskBaseVM interface:
/**
 * @member {String} cronExpression
 */
CreateTaskBaseVM.prototype['cronExpression'] = undefined;
/**
 * @member {Date} delayedRunTime
 */
CreateTaskBaseVM.prototype['delayedRunTime'] = undefined;
/**
 * @member {String} name
 */
CreateTaskBaseVM.prototype['name'] = undefined;
/**
 * @member {String} subscriptionId
 */
CreateTaskBaseVM.prototype['subscriptionId'] = undefined;
/**
 * @member {String} $t
 */
CreateTaskBaseVM.prototype['$t'] = undefined;




export default CreateTransformTaskBaseVM;

