/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteApiKeyVM model module.
 * @module models/DeleteApiKeyVM
 * @version v1
 */
class DeleteApiKeyVM {
    /**
     * Constructs a new <code>DeleteApiKeyVM</code>.
     * @alias module:models/DeleteApiKeyVM
     * @param apiKey {String} 
     */
    constructor(apiKey) { 
        
        DeleteApiKeyVM.initialize(this, apiKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apiKey) { 
        obj['apiKey'] = apiKey;
    }

    /**
     * Constructs a <code>DeleteApiKeyVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/DeleteApiKeyVM} obj Optional instance to populate.
     * @return {module:models/DeleteApiKeyVM} The populated <code>DeleteApiKeyVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteApiKeyVM();

            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteApiKeyVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteApiKeyVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteApiKeyVM.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['apiKey'] && !(typeof data['apiKey'] === 'string' || data['apiKey'] instanceof String)) {
            throw new Error("Expected the field `apiKey` to be a primitive type in the JSON string but got " + data['apiKey']);
        }

        return true;
    }


}

DeleteApiKeyVM.RequiredProperties = ["apiKey"];

/**
 * @member {String} apiKey
 */
DeleteApiKeyVM.prototype['apiKey'] = undefined;






export default DeleteApiKeyVM;

