/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportFormat from './ExportFormat';

/**
 * The ExportTemplateVM model module.
 * @module models/ExportTemplateVM
 * @version v1
 */
class ExportTemplateVM {
    /**
     * Constructs a new <code>ExportTemplateVM</code>.
     * @alias module:models/ExportTemplateVM
     */
    constructor() { 
        
        ExportTemplateVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExportTemplateVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ExportTemplateVM} obj Optional instance to populate.
     * @return {module:models/ExportTemplateVM} The populated <code>ExportTemplateVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportTemplateVM();

            if (data.hasOwnProperty('fileName')) {
                obj['fileName'] = ApiClient.convertToType(data['fileName'], 'String');
            }
            if (data.hasOwnProperty('folderId')) {
                obj['folderId'] = ApiClient.convertToType(data['folderId'], 'String');
            }
            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('pagesCount')) {
                obj['pagesCount'] = ApiClient.convertToType(data['pagesCount'], 'Number');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ExportFormat.constructFromObject(data['format']);
            }
            if (data.hasOwnProperty('exportParameters')) {
                obj['exportParameters'] = ApiClient.convertToType(data['exportParameters'], {'String': 'String'});
            }
            if (data.hasOwnProperty('reportParameters')) {
                obj['reportParameters'] = ApiClient.convertToType(data['reportParameters'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {String} fileName
 */
ExportTemplateVM.prototype['fileName'] = undefined;

/**
 * @member {String} folderId
 */
ExportTemplateVM.prototype['folderId'] = undefined;

/**
 * @member {String} locale
 */
ExportTemplateVM.prototype['locale'] = undefined;

/**
 * @member {Number} pagesCount
 */
ExportTemplateVM.prototype['pagesCount'] = undefined;

/**
 * @member {module:models/ExportFormat} format
 */
ExportTemplateVM.prototype['format'] = undefined;

/**
 * @member {Object.<String, String>} exportParameters
 */
ExportTemplateVM.prototype['exportParameters'] = undefined;

/**
 * @member {Object.<String, String>} reportParameters
 */
ExportTemplateVM.prototype['reportParameters'] = undefined;






export default ExportTemplateVM;

