/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportReportTaskVM from './ExportReportTaskVM';

/**
 * The ExportTemplateTaskVM model module.
 * @module models/ExportTemplateTaskVM
 * @version v1
 */
class ExportTemplateTaskVM {
    /**
     * Constructs a new <code>ExportTemplateTaskVM</code>.
     * @alias module:models/ExportTemplateTaskVM
     * @extends module:models/ExportReportTaskVM
     * @implements module:models/ExportReportTaskVM
     * @param t {String} 
     */
    constructor(t) { 
        ExportReportTaskVM.initialize(this, t);
        ExportTemplateTaskVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
    }

    /**
     * Constructs a <code>ExportTemplateTaskVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ExportTemplateTaskVM} obj Optional instance to populate.
     * @return {module:models/ExportTemplateTaskVM} The populated <code>ExportTemplateTaskVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportTemplateTaskVM();
            ExportReportTaskVM.constructFromObject(data, obj);
            ExportReportTaskVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('reportParameters')) {
                obj['reportParameters'] = ApiClient.convertToType(data['reportParameters'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExportTemplateTaskVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExportTemplateTaskVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExportTemplateTaskVM.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ExportTemplateTaskVM.RequiredProperties = ["$t"];

/**
 * @member {Object.<String, String>} reportParameters
 */
ExportTemplateTaskVM.prototype['reportParameters'] = undefined;


// Implement ExportReportTaskVM interface:
/**
 * @member {String} cronExpression
 */
ExportReportTaskVM.prototype['cronExpression'] = undefined;
/**
 * @member {Date} delayedRunTime
 */
ExportReportTaskVM.prototype['delayedRunTime'] = undefined;
/**
 * @member {Date} delayedWasRunTime
 */
ExportReportTaskVM.prototype['delayedWasRunTime'] = undefined;
/**
 * @member {String} id
 */
ExportReportTaskVM.prototype['id'] = undefined;
/**
 * @member {String} name
 */
ExportReportTaskVM.prototype['name'] = undefined;
/**
 * @member {Date} recurrentRunTime
 */
ExportReportTaskVM.prototype['recurrentRunTime'] = undefined;
/**
 * @member {Date} recurrentWasRunTime
 */
ExportReportTaskVM.prototype['recurrentWasRunTime'] = undefined;
/**
 * @member {String} subscriptionId
 */
ExportReportTaskVM.prototype['subscriptionId'] = undefined;
/**
 * @member {String} $t
 */
ExportReportTaskVM.prototype['$t'] = undefined;




export default ExportTemplateTaskVM;

