/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportFormat from './ExportFormat';
import FileStatus from './FileStatus';
import FileStatusReason from './FileStatusReason';
import FileType from './FileType';
import FileVM from './FileVM';

/**
 * The ExportVM model module.
 * @module models/ExportVM
 * @version v1
 */
class ExportVM {
    /**
     * Constructs a new <code>ExportVM</code>.
     * @alias module:models/ExportVM
     * @extends module:models/FileVM
     * @implements module:models/FileVM
     * @param t {String} 
     */
    constructor(t) { 
        FileVM.initialize(this, t);
        ExportVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>ExportVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ExportVM} obj Optional instance to populate.
     * @return {module:models/ExportVM} The populated <code>ExportVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportVM();
            FileVM.constructFromObject(data, obj);
            FileVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('format')) {
                obj['format'] = ExportFormat.constructFromObject(data['format']);
            }
            if (data.hasOwnProperty('reportId')) {
                obj['reportId'] = ApiClient.convertToType(data['reportId'], 'String');
            }
            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExportVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExportVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExportVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['reportId'] && !(typeof data['reportId'] === 'string' || data['reportId'] instanceof String)) {
            throw new Error("Expected the field `reportId` to be a primitive type in the JSON string but got " + data['reportId']);
        }
        // ensure the json data is a string
        if (data['templateId'] && !(typeof data['templateId'] === 'string' || data['templateId'] instanceof String)) {
            throw new Error("Expected the field `templateId` to be a primitive type in the JSON string but got " + data['templateId']);
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

ExportVM.RequiredProperties = ["$t"];

/**
 * @member {module:models/ExportFormat} format
 */
ExportVM.prototype['format'] = undefined;

/**
 * @member {String} reportId
 */
ExportVM.prototype['reportId'] = undefined;

/**
 * @member {String} templateId
 */
ExportVM.prototype['templateId'] = undefined;

/**
 * @member {String} $t
 */
ExportVM.prototype['$t'] = undefined;


// Implement FileVM interface:
/**
 * @member {String} $t
 */
FileVM.prototype['$t'] = undefined;




export default ExportVM;

