/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileCreateVM from './FileCreateVM';

/**
 * The ExportCreateVM model module.
 * @module models/ExportCreateVM
 * @version v1
 */
class ExportCreateVM {
    /**
     * Constructs a new <code>ExportCreateVM</code>.
     * @alias module:models/ExportCreateVM
     * @extends module:models/FileCreateVM
     * @implements module:models/FileCreateVM
     */
    constructor() { 
        FileCreateVM.initialize(this);
        ExportCreateVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExportCreateVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ExportCreateVM} obj Optional instance to populate.
     * @return {module:models/ExportCreateVM} The populated <code>ExportCreateVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportCreateVM();
            FileCreateVM.constructFromObject(data, obj);
            FileCreateVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('reportId')) {
                obj['reportId'] = ApiClient.convertToType(data['reportId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExportCreateVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExportCreateVM</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['templateId'] && !(typeof data['templateId'] === 'string' || data['templateId'] instanceof String)) {
            throw new Error("Expected the field `templateId` to be a primitive type in the JSON string but got " + data['templateId']);
        }
        // ensure the json data is a string
        if (data['reportId'] && !(typeof data['reportId'] === 'string' || data['reportId'] instanceof String)) {
            throw new Error("Expected the field `reportId` to be a primitive type in the JSON string but got " + data['reportId']);
        }

        return true;
    }


}



/**
 * @member {String} templateId
 */
ExportCreateVM.prototype['templateId'] = undefined;

/**
 * @member {String} reportId
 */
ExportCreateVM.prototype['reportId'] = undefined;


// Implement FileCreateVM interface:
/**
 * @member {String} name
 */
FileCreateVM.prototype['name'] = undefined;
/**
 * @member {Array.<String>} tags
 */
FileCreateVM.prototype['tags'] = undefined;
/**
 * @member {Blob} icon
 */
FileCreateVM.prototype['icon'] = undefined;
/**
 * @member {Blob} content
 */
FileCreateVM.prototype['content'] = undefined;




export default ExportCreateVM;

