/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaskBaseVM from './TaskBaseVM';

/**
 * The FetchTaskVM model module.
 * @module models/FetchTaskVM
 * @version v1
 */
class FetchTaskVM {
    /**
     * Constructs a new <code>FetchTaskVM</code>.
     * @alias module:models/FetchTaskVM
     * @extends module:models/TaskBaseVM
     * @implements module:models/TaskBaseVM
     * @param t {String} 
     */
    constructor(t) { 
        TaskBaseVM.initialize(this, t);
        FetchTaskVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
    }

    /**
     * Constructs a <code>FetchTaskVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/FetchTaskVM} obj Optional instance to populate.
     * @return {module:models/FetchTaskVM} The populated <code>FetchTaskVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FetchTaskVM();
            TaskBaseVM.constructFromObject(data, obj);
            TaskBaseVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('dataSourceId')) {
                obj['dataSourceId'] = ApiClient.convertToType(data['dataSourceId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FetchTaskVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FetchTaskVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FetchTaskVM.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dataSourceId'] && !(typeof data['dataSourceId'] === 'string' || data['dataSourceId'] instanceof String)) {
            throw new Error("Expected the field `dataSourceId` to be a primitive type in the JSON string but got " + data['dataSourceId']);
        }

        return true;
    }


}

FetchTaskVM.RequiredProperties = ["$t"];

/**
 * @member {String} dataSourceId
 */
FetchTaskVM.prototype['dataSourceId'] = undefined;


// Implement TaskBaseVM interface:
/**
 * @member {String} cronExpression
 */
TaskBaseVM.prototype['cronExpression'] = undefined;
/**
 * @member {Date} delayedRunTime
 */
TaskBaseVM.prototype['delayedRunTime'] = undefined;
/**
 * @member {Date} delayedWasRunTime
 */
TaskBaseVM.prototype['delayedWasRunTime'] = undefined;
/**
 * @member {String} id
 */
TaskBaseVM.prototype['id'] = undefined;
/**
 * @member {String} name
 */
TaskBaseVM.prototype['name'] = undefined;
/**
 * @member {Date} recurrentRunTime
 */
TaskBaseVM.prototype['recurrentRunTime'] = undefined;
/**
 * @member {Date} recurrentWasRunTime
 */
TaskBaseVM.prototype['recurrentWasRunTime'] = undefined;
/**
 * @member {String} subscriptionId
 */
TaskBaseVM.prototype['subscriptionId'] = undefined;
/**
 * @member {String} $t
 */
TaskBaseVM.prototype['$t'] = undefined;




export default FetchTaskVM;

