/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileVM from './FileVM';
import FileVMFilesVMBase from './FileVMFilesVMBase';

/**
 * The FilesVM model module.
 * @module models/FilesVM
 * @version v1
 */
class FilesVM {
    /**
     * Constructs a new <code>FilesVM</code>.
     * @alias module:models/FilesVM
     * @extends module:models/FileVMFilesVMBase
     * @implements module:models/FileVMFilesVMBase
     */
    constructor() { 
        FileVMFilesVMBase.initialize(this);
        FilesVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FilesVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/FilesVM} obj Optional instance to populate.
     * @return {module:models/FilesVM} The populated <code>FilesVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FilesVM();
            FileVMFilesVMBase.constructFromObject(data, obj);
            FileVMFilesVMBase.constructFromObject(data, obj);

        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FilesVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FilesVM</code>.
     */
    static validateJSON(data) {

        return true;
    }


}




// Implement FileVMFilesVMBase interface:
/**
 * @member {Array.<module:models/FileVM>} files
 */
FileVMFilesVMBase.prototype['files'] = undefined;
/**
 * @member {Number} count
 */
FileVMFilesVMBase.prototype['count'] = undefined;
/**
 * @member {Number} skip
 */
FileVMFilesVMBase.prototype['skip'] = undefined;
/**
 * @member {Number} take
 */
FileVMFilesVMBase.prototype['take'] = undefined;




export default FilesVM;

