/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppMixins from './AppMixins';

/**
 * The FrontendApp model module.
 * @module models/FrontendApp
 * @version v1
 */
class FrontendApp {
    /**
     * Constructs a new <code>FrontendApp</code>.
     * @alias module:models/FrontendApp
     */
    constructor() { 
        
        FrontendApp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FrontendApp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/FrontendApp} obj Optional instance to populate.
     * @return {module:models/FrontendApp} The populated <code>FrontendApp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FrontendApp();

            if (data.hasOwnProperty('mixins')) {
                obj['mixins'] = AppMixins.constructFromObject(data['mixins']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FrontendApp</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FrontendApp</code>.
     */
    static validateJSON(data) {
        // validate the optional field `mixins`
        if (data['mixins']) { // data not null
          AppMixins.validateJSON(data['mixins']);
        }

        return true;
    }


}



/**
 * @member {module:models/AppMixins} mixins
 */
FrontendApp.prototype['mixins'] = undefined;






export default FrontendApp;

