/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PreviewReportVM model module.
 * @module models/PreviewReportVM
 * @version v1
 */
class PreviewReportVM {
    /**
     * Constructs a new <code>PreviewReportVM</code>.
     * @alias module:models/PreviewReportVM
     */
    constructor() { 
        
        PreviewReportVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PreviewReportVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/PreviewReportVM} obj Optional instance to populate.
     * @return {module:models/PreviewReportVM} The populated <code>PreviewReportVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PreviewReportVM();

            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('cacheTolerance')) {
                obj['cacheTolerance'] = ApiClient.convertToType(data['cacheTolerance'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PreviewReportVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PreviewReportVM</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['locale'] && !(typeof data['locale'] === 'string' || data['locale'] instanceof String)) {
            throw new Error("Expected the field `locale` to be a primitive type in the JSON string but got " + data['locale']);
        }

        return true;
    }


}



/**
 * @member {String} locale
 */
PreviewReportVM.prototype['locale'] = undefined;

/**
 * @member {Number} cacheTolerance
 * @default 300
 */
PreviewReportVM.prototype['cacheTolerance'] = 300;






export default PreviewReportVM;

