/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ProblemLevel.
* @enum {}
* @readonly
*/
export default class ProblemLevel {
    
        /**
         * value: "None"
         * @const
         */
        "None" = "None";

    
        /**
         * value: "Information"
         * @const
         */
        "Information" = "Information";

    
        /**
         * value: "Warning"
         * @const
         */
        "Warning" = "Warning";

    
        /**
         * value: "Critical"
         * @const
         */
        "Critical" = "Critical";

    

    /**
    * Returns a <code>ProblemLevel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/ProblemLevel} The enum <code>ProblemLevel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

