/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SaveMode from './SaveMode';

/**
 * The ReportInfo model module.
 * @module models/ReportInfo
 * @version v1
 */
class ReportInfo {
    /**
     * Constructs a new <code>ReportInfo</code>.
     * @alias module:models/ReportInfo
     */
    constructor() { 
        
        ReportInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ReportInfo} obj Optional instance to populate.
     * @return {module:models/ReportInfo} The populated <code>ReportInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportInfo();

            if (data.hasOwnProperty('author')) {
                obj['author'] = ApiClient.convertToType(data['author'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('creatorVersion')) {
                obj['creatorVersion'] = ApiClient.convertToType(data['creatorVersion'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('picture')) {
                obj['picture'] = ApiClient.convertToType(data['picture'], 'Blob');
            }
            if (data.hasOwnProperty('previewPictureRatio')) {
                obj['previewPictureRatio'] = ApiClient.convertToType(data['previewPictureRatio'], 'Number');
            }
            if (data.hasOwnProperty('saveMode')) {
                obj['saveMode'] = SaveMode.constructFromObject(data['saveMode']);
            }
            if (data.hasOwnProperty('savePreviewPicture')) {
                obj['savePreviewPicture'] = ApiClient.convertToType(data['savePreviewPicture'], 'Boolean');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReportInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReportInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['author'] && !(typeof data['author'] === 'string' || data['author'] instanceof String)) {
            throw new Error("Expected the field `author` to be a primitive type in the JSON string but got " + data['author']);
        }
        // ensure the json data is a string
        if (data['creatorVersion'] && !(typeof data['creatorVersion'] === 'string' || data['creatorVersion'] instanceof String)) {
            throw new Error("Expected the field `creatorVersion` to be a primitive type in the JSON string but got " + data['creatorVersion']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['tag'] && !(typeof data['tag'] === 'string' || data['tag'] instanceof String)) {
            throw new Error("Expected the field `tag` to be a primitive type in the JSON string but got " + data['tag']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }

        return true;
    }


}



/**
 * @member {String} author
 */
ReportInfo.prototype['author'] = undefined;

/**
 * @member {Date} created
 */
ReportInfo.prototype['created'] = undefined;

/**
 * @member {String} creatorVersion
 */
ReportInfo.prototype['creatorVersion'] = undefined;

/**
 * @member {String} description
 */
ReportInfo.prototype['description'] = undefined;

/**
 * @member {Date} modified
 */
ReportInfo.prototype['modified'] = undefined;

/**
 * @member {String} name
 */
ReportInfo.prototype['name'] = undefined;

/**
 * @member {Blob} picture
 */
ReportInfo.prototype['picture'] = undefined;

/**
 * @member {Number} previewPictureRatio
 */
ReportInfo.prototype['previewPictureRatio'] = undefined;

/**
 * @member {module:models/SaveMode} saveMode
 */
ReportInfo.prototype['saveMode'] = undefined;

/**
 * @member {Boolean} savePreviewPicture
 */
ReportInfo.prototype['savePreviewPicture'] = undefined;

/**
 * @member {String} tag
 */
ReportInfo.prototype['tag'] = undefined;

/**
 * @member {String} version
 */
ReportInfo.prototype['version'] = undefined;






export default ReportInfo;

