/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FolderCreateVM from './FolderCreateVM';

/**
 * The ReportFolderCreateVM model module.
 * @module models/ReportFolderCreateVM
 * @version v1
 */
class ReportFolderCreateVM {
    /**
     * Constructs a new <code>ReportFolderCreateVM</code>.
     * @alias module:models/ReportFolderCreateVM
     * @extends module:models/FolderCreateVM
     * @implements module:models/FolderCreateVM
     * @param t {String} 
     */
    constructor(t) { 
        FolderCreateVM.initialize(this, t);
        ReportFolderCreateVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>ReportFolderCreateVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ReportFolderCreateVM} obj Optional instance to populate.
     * @return {module:models/ReportFolderCreateVM} The populated <code>ReportFolderCreateVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportFolderCreateVM();
            FolderCreateVM.constructFromObject(data, obj);
            FolderCreateVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReportFolderCreateVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReportFolderCreateVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReportFolderCreateVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

ReportFolderCreateVM.RequiredProperties = ["$t"];

/**
 * @member {String} $t
 */
ReportFolderCreateVM.prototype['$t'] = undefined;


// Implement FolderCreateVM interface:
/**
 * @member {String} $t
 */
FolderCreateVM.prototype['$t'] = undefined;




export default ReportFolderCreateVM;

