/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileVM from './FileVM';
import ReportInfo from './ReportInfo';

/**
 * The ReportVM model module.
 * @module models/ReportVM
 * @version v1
 */
class ReportVM {
    /**
     * Constructs a new <code>ReportVM</code>.
     * @alias module:models/ReportVM
     * @implements module:models/FileVM
     */
    constructor() { 
        FileVM.initialize(this);
        ReportVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ReportVM} obj Optional instance to populate.
     * @return {module:models/ReportVM} The populated <code>ReportVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportVM();
            FileVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('reportInfo')) {
                obj['reportInfo'] = ReportInfo.constructFromObject(data['reportInfo']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('createdTime')) {
                obj['createdTime'] = ApiClient.convertToType(data['createdTime'], 'Date');
            }
            if (data.hasOwnProperty('creatorUserId')) {
                obj['creatorUserId'] = ApiClient.convertToType(data['creatorUserId'], 'String');
            }
            if (data.hasOwnProperty('editedTime')) {
                obj['editedTime'] = ApiClient.convertToType(data['editedTime'], 'Date');
            }
            if (data.hasOwnProperty('editorUserId')) {
                obj['editorUserId'] = ApiClient.convertToType(data['editorUserId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} templateId
 */
ReportVM.prototype['templateId'] = undefined;

/**
 * @member {module:models/ReportInfo} reportInfo
 */
ReportVM.prototype['reportInfo'] = undefined;

/**
 * @member {String} id
 */
ReportVM.prototype['id'] = undefined;

/**
 * @member {Date} createdTime
 */
ReportVM.prototype['createdTime'] = undefined;

/**
 * @member {String} creatorUserId
 */
ReportVM.prototype['creatorUserId'] = undefined;

/**
 * @member {Date} editedTime
 */
ReportVM.prototype['editedTime'] = undefined;

/**
 * @member {String} editorUserId
 */
ReportVM.prototype['editorUserId'] = undefined;


// Implement FileVM interface:
/**
 * @member {String} id
 */
FileVM.prototype['id'] = undefined;
/**
 * @member {Date} createdTime
 */
FileVM.prototype['createdTime'] = undefined;
/**
 * @member {String} creatorUserId
 */
FileVM.prototype['creatorUserId'] = undefined;
/**
 * @member {Date} editedTime
 */
FileVM.prototype['editedTime'] = undefined;
/**
 * @member {String} editorUserId
 */
FileVM.prototype['editorUserId'] = undefined;




export default ReportVM;

