/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RunTaskBaseVM from './RunTaskBaseVM';

/**
 * The RunThumbnailTemplateTaskVM model module.
 * @module models/RunThumbnailTemplateTaskVM
 * @version v1
 */
class RunThumbnailTemplateTaskVM {
    /**
     * Constructs a new <code>RunThumbnailTemplateTaskVM</code>.
     * @alias module:models/RunThumbnailTemplateTaskVM
     * @extends module:models/RunTaskBaseVM
     * @implements module:models/RunTaskBaseVM
     * @param t {String} 
     */
    constructor(t) { 
        RunTaskBaseVM.initialize(this, t);
        RunThumbnailTemplateTaskVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>RunThumbnailTemplateTaskVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/RunThumbnailTemplateTaskVM} obj Optional instance to populate.
     * @return {module:models/RunThumbnailTemplateTaskVM} The populated <code>RunThumbnailTemplateTaskVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunThumbnailTemplateTaskVM();
            RunTaskBaseVM.constructFromObject(data, obj);
            RunTaskBaseVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RunThumbnailTemplateTaskVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RunThumbnailTemplateTaskVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RunThumbnailTemplateTaskVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['templateId'] && !(typeof data['templateId'] === 'string' || data['templateId'] instanceof String)) {
            throw new Error("Expected the field `templateId` to be a primitive type in the JSON string but got " + data['templateId']);
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

RunThumbnailTemplateTaskVM.RequiredProperties = ["$t"];

/**
 * @member {String} templateId
 */
RunThumbnailTemplateTaskVM.prototype['templateId'] = undefined;

/**
 * @member {String} $t
 */
RunThumbnailTemplateTaskVM.prototype['$t'] = undefined;


// Implement RunTaskBaseVM interface:
/**
 * @member {String} $t
 */
RunTaskBaseVM.prototype['$t'] = undefined;




export default RunThumbnailTemplateTaskVM;

