/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OutputFileVM from './OutputFileVM';
import RunInputFileVM from './RunInputFileVM';
import RunTaskBaseVM from './RunTaskBaseVM';
import RunTransportTaskBaseVM from './RunTransportTaskBaseVM';
import TaskType from './TaskType';

/**
 * The RunTransformTaskBaseVM model module.
 * @module models/RunTransformTaskBaseVM
 * @version v1
 */
class RunTransformTaskBaseVM {
    /**
     * Constructs a new <code>RunTransformTaskBaseVM</code>.
     * @alias module:models/RunTransformTaskBaseVM
     * @implements module:models/RunTaskBaseVM
     */
    constructor() { 
        RunTaskBaseVM.initialize(this);
        RunTransformTaskBaseVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RunTransformTaskBaseVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/RunTransformTaskBaseVM} obj Optional instance to populate.
     * @return {module:models/RunTransformTaskBaseVM} The populated <code>RunTransformTaskBaseVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunTransformTaskBaseVM();
            RunTaskBaseVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('inputFile')) {
                obj['inputFile'] = RunInputFileVM.constructFromObject(data['inputFile']);
            }
            if (data.hasOwnProperty('outputFile')) {
                obj['outputFile'] = OutputFileVM.constructFromObject(data['outputFile']);
            }
            if (data.hasOwnProperty('transports')) {
                obj['transports'] = ApiClient.convertToType(data['transports'], [RunTransportTaskBaseVM]);
            }
            if (data.hasOwnProperty('subscriptionId')) {
                obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = TaskType.constructFromObject(data['type']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} locale
 */
RunTransformTaskBaseVM.prototype['locale'] = undefined;

/**
 * @member {module:models/RunInputFileVM} inputFile
 */
RunTransformTaskBaseVM.prototype['inputFile'] = undefined;

/**
 * @member {module:models/OutputFileVM} outputFile
 */
RunTransformTaskBaseVM.prototype['outputFile'] = undefined;

/**
 * @member {Array.<module:models/RunTransportTaskBaseVM>} transports
 */
RunTransformTaskBaseVM.prototype['transports'] = undefined;

/**
 * @member {String} subscriptionId
 */
RunTransformTaskBaseVM.prototype['subscriptionId'] = undefined;

/**
 * @member {module:models/TaskType} type
 */
RunTransformTaskBaseVM.prototype['type'] = undefined;


// Implement RunTaskBaseVM interface:
/**
 * @member {String} subscriptionId
 */
RunTaskBaseVM.prototype['subscriptionId'] = undefined;
/**
 * @member {module:models/TaskType} type
 */
RunTaskBaseVM.prototype['type'] = undefined;




export default RunTransformTaskBaseVM;

