/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RunTaskBaseVM from './RunTaskBaseVM';

/**
 * The RunThumbnailReportTaskVM model module.
 * @module models/RunThumbnailReportTaskVM
 * @version v1
 */
class RunThumbnailReportTaskVM {
    /**
     * Constructs a new <code>RunThumbnailReportTaskVM</code>.
     * @alias module:models/RunThumbnailReportTaskVM
     * @extends module:models/RunTaskBaseVM
     * @implements module:models/RunTaskBaseVM
     * @param t {String} 
     */
    constructor(t) { 
        RunTaskBaseVM.initialize(this, t);
        RunThumbnailReportTaskVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>RunThumbnailReportTaskVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/RunThumbnailReportTaskVM} obj Optional instance to populate.
     * @return {module:models/RunThumbnailReportTaskVM} The populated <code>RunThumbnailReportTaskVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunThumbnailReportTaskVM();
            RunTaskBaseVM.constructFromObject(data, obj);
            RunTaskBaseVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('reportId')) {
                obj['reportId'] = ApiClient.convertToType(data['reportId'], 'String');
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RunThumbnailReportTaskVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RunThumbnailReportTaskVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RunThumbnailReportTaskVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['reportId'] && !(typeof data['reportId'] === 'string' || data['reportId'] instanceof String)) {
            throw new Error("Expected the field `reportId` to be a primitive type in the JSON string but got " + data['reportId']);
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

RunThumbnailReportTaskVM.RequiredProperties = ["$t"];

/**
 * @member {String} reportId
 */
RunThumbnailReportTaskVM.prototype['reportId'] = undefined;

/**
 * @member {String} $t
 */
RunThumbnailReportTaskVM.prototype['$t'] = undefined;


// Implement RunTaskBaseVM interface:
/**
 * @member {String} $t
 */
RunTaskBaseVM.prototype['$t'] = undefined;




export default RunThumbnailReportTaskVM;

