/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudBaseVM from './CloudBaseVM';
import TaskPermissionCRUDVM from './TaskPermissionCRUDVM';

/**
 * The TaskPermissionsCRUDVM model module.
 * @module models/TaskPermissionsCRUDVM
 * @version v1
 */
class TaskPermissionsCRUDVM {
    /**
     * Constructs a new <code>TaskPermissionsCRUDVM</code>.
     * @alias module:models/TaskPermissionsCRUDVM
     * @extends module:models/CloudBaseVM
     * @implements module:models/CloudBaseVM
     * @param t {String} 
     */
    constructor(t) { 
        CloudBaseVM.initialize(this, t);
        TaskPermissionsCRUDVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>TaskPermissionsCRUDVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TaskPermissionsCRUDVM} obj Optional instance to populate.
     * @return {module:models/TaskPermissionsCRUDVM} The populated <code>TaskPermissionsCRUDVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskPermissionsCRUDVM();
            CloudBaseVM.constructFromObject(data, obj);
            CloudBaseVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('ownerId')) {
                obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = TaskPermissionCRUDVM.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], {'String': TaskPermissionCRUDVM});
            }
            if (data.hasOwnProperty('other')) {
                obj['other'] = TaskPermissionCRUDVM.constructFromObject(data['other']);
            }
            if (data.hasOwnProperty('anon')) {
                obj['anon'] = TaskPermissionCRUDVM.constructFromObject(data['anon']);
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TaskPermissionsCRUDVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TaskPermissionsCRUDVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TaskPermissionsCRUDVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['ownerId'] && !(typeof data['ownerId'] === 'string' || data['ownerId'] instanceof String)) {
            throw new Error("Expected the field `ownerId` to be a primitive type in the JSON string but got " + data['ownerId']);
        }
        // validate the optional field `owner`
        if (data['owner']) { // data not null
          TaskPermissionCRUDVM.validateJSON(data['owner']);
        }
        // validate the optional field `other`
        if (data['other']) { // data not null
          TaskPermissionCRUDVM.validateJSON(data['other']);
        }
        // validate the optional field `anon`
        if (data['anon']) { // data not null
          TaskPermissionCRUDVM.validateJSON(data['anon']);
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

TaskPermissionsCRUDVM.RequiredProperties = ["$t"];

/**
 * @member {String} ownerId
 */
TaskPermissionsCRUDVM.prototype['ownerId'] = undefined;

/**
 * @member {module:models/TaskPermissionCRUDVM} owner
 */
TaskPermissionsCRUDVM.prototype['owner'] = undefined;

/**
 * @member {Object.<String, module:models/TaskPermissionCRUDVM>} groups
 */
TaskPermissionsCRUDVM.prototype['groups'] = undefined;

/**
 * @member {module:models/TaskPermissionCRUDVM} other
 */
TaskPermissionsCRUDVM.prototype['other'] = undefined;

/**
 * @member {module:models/TaskPermissionCRUDVM} anon
 */
TaskPermissionsCRUDVM.prototype['anon'] = undefined;

/**
 * @member {String} $t
 */
TaskPermissionsCRUDVM.prototype['$t'] = undefined;


// Implement CloudBaseVM interface:
/**
 * @member {String} $t
 */
CloudBaseVM.prototype['$t'] = undefined;




export default TaskPermissionsCRUDVM;

