/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TaskEnd model module.
 * @module models/TaskEnd
 * @version v1
 */
class TaskEnd {
    /**
     * Constructs a new <code>TaskEnd</code>.
     * @alias module:models/TaskEnd
     */
    constructor() { 
        
        TaskEnd.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaskEnd</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TaskEnd} obj Optional instance to populate.
     * @return {module:models/TaskEnd} The populated <code>TaskEnd</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskEnd();

            if (data.hasOwnProperty('after')) {
                obj['after'] = ApiClient.convertToType(data['after'], 'Number');
            }
            if (data.hasOwnProperty('on')) {
                obj['on'] = ApiClient.convertToType(data['on'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TaskEnd</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TaskEnd</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} after
 */
TaskEnd.prototype['after'] = undefined;

/**
 * @member {Date} on
 */
TaskEnd.prototype['on'] = undefined;






export default TaskEnd;

