/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TemplateVM from './TemplateVM';

/**
 * The TemplatesVM model module.
 * @module models/TemplatesVM
 * @version v1
 */
class TemplatesVM {
    /**
     * Constructs a new <code>TemplatesVM</code>.
     * @alias module:models/TemplatesVM
     */
    constructor() { 
        
        TemplatesVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TemplatesVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TemplatesVM} obj Optional instance to populate.
     * @return {module:models/TemplatesVM} The populated <code>TemplatesVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplatesVM();

            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], [TemplateVM]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('skip')) {
                obj['skip'] = ApiClient.convertToType(data['skip'], 'Number');
            }
            if (data.hasOwnProperty('take')) {
                obj['take'] = ApiClient.convertToType(data['take'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:models/TemplateVM>} files
 */
TemplatesVM.prototype['files'] = undefined;

/**
 * @member {Number} count
 */
TemplatesVM.prototype['count'] = undefined;

/**
 * @member {Number} skip
 */
TemplatesVM.prototype['skip'] = undefined;

/**
 * @member {Number} take
 */
TemplatesVM.prototype['take'] = undefined;






export default TemplatesVM;

