/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileCreateFormVM from './FileCreateFormVM';

/**
 * The TemplateCreateFormVM model module.
 * @module models/TemplateCreateFormVM
 * @version v1
 */
class TemplateCreateFormVM {
    /**
     * Constructs a new <code>TemplateCreateFormVM</code>.
     * @alias module:models/TemplateCreateFormVM
     * @extends module:models/FileCreateFormVM
     * @implements module:models/FileCreateFormVM
     * @param fileContent {File} 
     * @param t {String} 
     */
    constructor(fileContent, t) { 
        FileCreateFormVM.initialize(this, t);
        TemplateCreateFormVM.initialize(this, fileContent, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fileContent, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>TemplateCreateFormVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TemplateCreateFormVM} obj Optional instance to populate.
     * @return {module:models/TemplateCreateFormVM} The populated <code>TemplateCreateFormVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateCreateFormVM();
            FileCreateFormVM.constructFromObject(data, obj);
            FileCreateFormVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TemplateCreateFormVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TemplateCreateFormVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TemplateCreateFormVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

TemplateCreateFormVM.RequiredProperties = ["$t", "fileContent"];

/**
 * @member {String} $t
 */
TemplateCreateFormVM.prototype['$t'] = undefined;


// Implement FileCreateFormVM interface:
/**
 * @member {String} $t
 */
FileCreateFormVM.prototype['$t'] = undefined;




export default TemplateCreateFormVM;

