/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaskAdministrate from './TaskAdministrate';
import TaskPermissions from './TaskPermissions';

/**
 * The UpdateTaskPermissionsVM model module.
 * @module models/UpdateTaskPermissionsVM
 * @version v1
 */
class UpdateTaskPermissionsVM {
    /**
     * Constructs a new <code>UpdateTaskPermissionsVM</code>.
     * @alias module:models/UpdateTaskPermissionsVM
     * @param administrate {module:models/TaskAdministrate} 
     * @param newPermissions {module:models/TaskPermissions} 
     */
    constructor(administrate, newPermissions) { 
        
        UpdateTaskPermissionsVM.initialize(this, administrate, newPermissions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, administrate, newPermissions) { 
        obj['administrate'] = administrate;
        obj['newPermissions'] = newPermissions;
    }

    /**
     * Constructs a <code>UpdateTaskPermissionsVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/UpdateTaskPermissionsVM} obj Optional instance to populate.
     * @return {module:models/UpdateTaskPermissionsVM} The populated <code>UpdateTaskPermissionsVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateTaskPermissionsVM();

            if (data.hasOwnProperty('administrate')) {
                obj['administrate'] = TaskAdministrate.constructFromObject(data['administrate']);
            }
            if (data.hasOwnProperty('newPermissions')) {
                obj['newPermissions'] = TaskPermissions.constructFromObject(data['newPermissions']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateTaskPermissionsVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateTaskPermissionsVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateTaskPermissionsVM.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `newPermissions`
        if (data['newPermissions']) { // data not null
          TaskPermissions.validateJSON(data['newPermissions']);
        }

        return true;
    }


}

UpdateTaskPermissionsVM.RequiredProperties = ["administrate", "newPermissions"];

/**
 * @member {module:models/TaskAdministrate} administrate
 */
UpdateTaskPermissionsVM.prototype['administrate'] = undefined;

/**
 * @member {module:models/TaskPermissions} newPermissions
 */
UpdateTaskPermissionsVM.prototype['newPermissions'] = undefined;






export default UpdateTaskPermissionsVM;

