/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DefaultPermissions from './DefaultPermissions';

/**
 * The UpdateSubscriptionVM model module.
 * @module models/UpdateSubscriptionVM
 * @version v1
 */
class UpdateSubscriptionVM {
    /**
     * Constructs a new <code>UpdateSubscriptionVM</code>.
     * @alias module:models/UpdateSubscriptionVM
     */
    constructor() { 
        
        UpdateSubscriptionVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateSubscriptionVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/UpdateSubscriptionVM} obj Optional instance to populate.
     * @return {module:models/UpdateSubscriptionVM} The populated <code>UpdateSubscriptionVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSubscriptionVM();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('defaultPermissions')) {
                obj['defaultPermissions'] = DefaultPermissions.constructFromObject(data['defaultPermissions']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
UpdateSubscriptionVM.prototype['name'] = undefined;

/**
 * @member {String} locale
 */
UpdateSubscriptionVM.prototype['locale'] = undefined;

/**
 * @member {module:models/DefaultPermissions} defaultPermissions
 */
UpdateSubscriptionVM.prototype['defaultPermissions'] = undefined;






export default UpdateSubscriptionVM;

