/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudBaseVM from './CloudBaseVM';

/**
 * The UpdateUserProfileVM model module.
 * @module models/UpdateUserProfileVM
 * @version v1
 */
class UpdateUserProfileVM {
    /**
     * Constructs a new <code>UpdateUserProfileVM</code>.
     * @alias module:models/UpdateUserProfileVM
     * @extends module:models/CloudBaseVM
     * @implements module:models/CloudBaseVM
     * @param t {String} 
     */
    constructor(t) { 
        CloudBaseVM.initialize(this, t);
        UpdateUserProfileVM.initialize(this, t);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, t) { 
        obj['$t'] = t;
    }

    /**
     * Constructs a <code>UpdateUserProfileVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/UpdateUserProfileVM} obj Optional instance to populate.
     * @return {module:models/UpdateUserProfileVM} The populated <code>UpdateUserProfileVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUserProfileVM();
            CloudBaseVM.constructFromObject(data, obj);
            CloudBaseVM.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('passwordNew')) {
                obj['passwordNew'] = ApiClient.convertToType(data['passwordNew'], 'String');
            }
            if (data.hasOwnProperty('passwordNew2')) {
                obj['passwordNew2'] = ApiClient.convertToType(data['passwordNew2'], 'String');
            }
            if (data.hasOwnProperty('$t')) {
                obj['$t'] = ApiClient.convertToType(data['$t'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateUserProfileVM</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateUserProfileVM</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateUserProfileVM.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['passwordNew'] && !(typeof data['passwordNew'] === 'string' || data['passwordNew'] instanceof String)) {
            throw new Error("Expected the field `passwordNew` to be a primitive type in the JSON string but got " + data['passwordNew']);
        }
        // ensure the json data is a string
        if (data['passwordNew2'] && !(typeof data['passwordNew2'] === 'string' || data['passwordNew2'] instanceof String)) {
            throw new Error("Expected the field `passwordNew2` to be a primitive type in the JSON string but got " + data['passwordNew2']);
        }
        // ensure the json data is a string
        if (data['$t'] && !(typeof data['$t'] === 'string' || data['$t'] instanceof String)) {
            throw new Error("Expected the field `$t` to be a primitive type in the JSON string but got " + data['$t']);
        }

        return true;
    }


}

UpdateUserProfileVM.RequiredProperties = ["$t"];

/**
 * @member {String} name
 */
UpdateUserProfileVM.prototype['name'] = undefined;

/**
 * @member {String} username
 */
UpdateUserProfileVM.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UpdateUserProfileVM.prototype['email'] = undefined;

/**
 * @member {String} passwordNew
 */
UpdateUserProfileVM.prototype['passwordNew'] = undefined;

/**
 * @member {String} passwordNew2
 */
UpdateUserProfileVM.prototype['passwordNew2'] = undefined;

/**
 * @member {String} $t
 */
UpdateUserProfileVM.prototype['$t'] = undefined;


// Implement CloudBaseVM interface:
/**
 * @member {String} $t
 */
CloudBaseVM.prototype['$t'] = undefined;




export default UpdateUserProfileVM;

