/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdminPermission from './AdminPermission';

/**
 * The UserVM model module.
 * @module models/UserVM
 * @version v1
 */
class UserVM {
    /**
     * Constructs a new <code>UserVM</code>.
     * @alias module:models/UserVM
     */
    constructor() { 
        
        UserVM.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/UserVM} obj Optional instance to populate.
     * @return {module:models/UserVM} The populated <code>UserVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserVM();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('subscriptions')) {
                obj['subscriptions'] = ApiClient.convertToType(data['subscriptions'], ['String']);
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], ['String']);
            }
            if (data.hasOwnProperty('adminPermission')) {
                obj['adminPermission'] = AdminPermission.constructFromObject(data['adminPermission']);
            }
            if (data.hasOwnProperty('isAdmin')) {
                obj['isAdmin'] = ApiClient.convertToType(data['isAdmin'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserVM.prototype['id'] = undefined;

/**
 * @member {Array.<String>} subscriptions
 */
UserVM.prototype['subscriptions'] = undefined;

/**
 * @member {Array.<String>} groups
 */
UserVM.prototype['groups'] = undefined;

/**
 * @member {module:models/AdminPermission} adminPermission
 */
UserVM.prototype['adminPermission'] = undefined;

/**
 * @member {Boolean} isAdmin
 */
UserVM.prototype['isAdmin'] = undefined;

/**
 * @member {String} name
 */
UserVM.prototype['name'] = undefined;

/**
 * @member {String} username
 */
UserVM.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UserVM.prototype['email'] = undefined;






export default UserVM;

