/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastreportCloudSdk);
  }
}(this, function(expect, FastreportCloudSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastreportCloudSdk.AdminSubscriptionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminSubscriptionsApi', function() {
    describe('adminSubscriptionsCreateSubscription', function() {
      it('should call adminSubscriptionsCreateSubscription successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsCreateSubscription
        //instance.adminSubscriptionsCreateSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsDeleteSubscription', function() {
      it('should call adminSubscriptionsDeleteSubscription successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsDeleteSubscription
        //instance.adminSubscriptionsDeleteSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsGetNewSibscriptionsPerMonth', function() {
      it('should call adminSubscriptionsGetNewSibscriptionsPerMonth successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsGetNewSibscriptionsPerMonth
        //instance.adminSubscriptionsGetNewSibscriptionsPerMonth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsGetPermissions', function() {
      it('should call adminSubscriptionsGetPermissions successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsGetPermissions
        //instance.adminSubscriptionsGetPermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsGetSubscription', function() {
      it('should call adminSubscriptionsGetSubscription successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsGetSubscription
        //instance.adminSubscriptionsGetSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsGetSubscriptions', function() {
      it('should call adminSubscriptionsGetSubscriptions successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsGetSubscriptions
        //instance.adminSubscriptionsGetSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsReCountSubscription', function() {
      it('should call adminSubscriptionsReCountSubscription successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsReCountSubscription
        //instance.adminSubscriptionsReCountSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsUpdatePermissions', function() {
      it('should call adminSubscriptionsUpdatePermissions successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsUpdatePermissions
        //instance.adminSubscriptionsUpdatePermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminSubscriptionsUpdateSubscription', function() {
      it('should call adminSubscriptionsUpdateSubscription successfully', function(done) {
        //uncomment below and update the code to test adminSubscriptionsUpdateSubscription
        //instance.adminSubscriptionsUpdateSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
