/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastreportCloudSdk);
  }
}(this, function(expect, FastreportCloudSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastreportCloudSdk.TemplatesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplatesApi', function() {
    describe('templateFolderAndFileGetCount', function() {
      it('should call templateFolderAndFileGetCount successfully', function(done) {
        //uncomment below and update the code to test templateFolderAndFileGetCount
        //instance.templateFolderAndFileGetCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFolderAndFileGetFoldersAndFiles', function() {
      it('should call templateFolderAndFileGetFoldersAndFiles successfully', function(done) {
        //uncomment below and update the code to test templateFolderAndFileGetFoldersAndFiles
        //instance.templateFolderAndFileGetFoldersAndFiles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersCopyFolder', function() {
      it('should call templateFoldersCopyFolder successfully', function(done) {
        //uncomment below and update the code to test templateFoldersCopyFolder
        //instance.templateFoldersCopyFolder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersDeleteFolder', function() {
      it('should call templateFoldersDeleteFolder successfully', function(done) {
        //uncomment below and update the code to test templateFoldersDeleteFolder
        //instance.templateFoldersDeleteFolder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersGetBreadcrumbs', function() {
      it('should call templateFoldersGetBreadcrumbs successfully', function(done) {
        //uncomment below and update the code to test templateFoldersGetBreadcrumbs
        //instance.templateFoldersGetBreadcrumbs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersGetFolder', function() {
      it('should call templateFoldersGetFolder successfully', function(done) {
        //uncomment below and update the code to test templateFoldersGetFolder
        //instance.templateFoldersGetFolder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersGetFolders', function() {
      it('should call templateFoldersGetFolders successfully', function(done) {
        //uncomment below and update the code to test templateFoldersGetFolders
        //instance.templateFoldersGetFolders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersGetFoldersCount', function() {
      it('should call templateFoldersGetFoldersCount successfully', function(done) {
        //uncomment below and update the code to test templateFoldersGetFoldersCount
        //instance.templateFoldersGetFoldersCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersGetPermissions', function() {
      it('should call templateFoldersGetPermissions successfully', function(done) {
        //uncomment below and update the code to test templateFoldersGetPermissions
        //instance.templateFoldersGetPermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersGetRootFolder', function() {
      it('should call templateFoldersGetRootFolder successfully', function(done) {
        //uncomment below and update the code to test templateFoldersGetRootFolder
        //instance.templateFoldersGetRootFolder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersMoveFolder', function() {
      it('should call templateFoldersMoveFolder successfully', function(done) {
        //uncomment below and update the code to test templateFoldersMoveFolder
        //instance.templateFoldersMoveFolder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersPostFolder', function() {
      it('should call templateFoldersPostFolder successfully', function(done) {
        //uncomment below and update the code to test templateFoldersPostFolder
        //instance.templateFoldersPostFolder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersRenameFolder', function() {
      it('should call templateFoldersRenameFolder successfully', function(done) {
        //uncomment below and update the code to test templateFoldersRenameFolder
        //instance.templateFoldersRenameFolder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersUpdateIcon', function() {
      it('should call templateFoldersUpdateIcon successfully', function(done) {
        //uncomment below and update the code to test templateFoldersUpdateIcon
        //instance.templateFoldersUpdateIcon(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersUpdatePermissions', function() {
      it('should call templateFoldersUpdatePermissions successfully', function(done) {
        //uncomment below and update the code to test templateFoldersUpdatePermissions
        //instance.templateFoldersUpdatePermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateFoldersUpdateTags', function() {
      it('should call templateFoldersUpdateTags successfully', function(done) {
        //uncomment below and update the code to test templateFoldersUpdateTags
        //instance.templateFoldersUpdateTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesCopyFile', function() {
      it('should call templatesCopyFile successfully', function(done) {
        //uncomment below and update the code to test templatesCopyFile
        //instance.templatesCopyFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesDeleteFile', function() {
      it('should call templatesDeleteFile successfully', function(done) {
        //uncomment below and update the code to test templatesDeleteFile
        //instance.templatesDeleteFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesExport', function() {
      it('should call templatesExport successfully', function(done) {
        //uncomment below and update the code to test templatesExport
        //instance.templatesExport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesGetFile', function() {
      it('should call templatesGetFile successfully', function(done) {
        //uncomment below and update the code to test templatesGetFile
        //instance.templatesGetFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesGetFilesCount', function() {
      it('should call templatesGetFilesCount successfully', function(done) {
        //uncomment below and update the code to test templatesGetFilesCount
        //instance.templatesGetFilesCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesGetFilesList', function() {
      it('should call templatesGetFilesList successfully', function(done) {
        //uncomment below and update the code to test templatesGetFilesList
        //instance.templatesGetFilesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesGetPermissions', function() {
      it('should call templatesGetPermissions successfully', function(done) {
        //uncomment below and update the code to test templatesGetPermissions
        //instance.templatesGetPermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesMoveFile', function() {
      it('should call templatesMoveFile successfully', function(done) {
        //uncomment below and update the code to test templatesMoveFile
        //instance.templatesMoveFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesPrepare', function() {
      it('should call templatesPrepare successfully', function(done) {
        //uncomment below and update the code to test templatesPrepare
        //instance.templatesPrepare(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesRenameFile', function() {
      it('should call templatesRenameFile successfully', function(done) {
        //uncomment below and update the code to test templatesRenameFile
        //instance.templatesRenameFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesUpdateIcon', function() {
      it('should call templatesUpdateIcon successfully', function(done) {
        //uncomment below and update the code to test templatesUpdateIcon
        //instance.templatesUpdateIcon(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesUpdatePermissions', function() {
      it('should call templatesUpdatePermissions successfully', function(done) {
        //uncomment below and update the code to test templatesUpdatePermissions
        //instance.templatesUpdatePermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesUpdateTags', function() {
      it('should call templatesUpdateTags successfully', function(done) {
        //uncomment below and update the code to test templatesUpdateTags
        //instance.templatesUpdateTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatesUploadFile', function() {
      it('should call templatesUploadFile successfully', function(done) {
        //uncomment below and update the code to test templatesUploadFile
        //instance.templatesUploadFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
